run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/kgateway-dev/krtequals

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
